import turtle as t
pen = t.Turtle()
t.bgcolor('red')
t.delay(10)
pen.color('yellow')
pen.begin_fill()
pen.left(40)
pen.forward(120)
pen.circle(80,190)
pen.right(100)
pen.circle(80,200 )
pen.forward(160)
pen.left(90)
pen.forward(20)
pen.setpos(-30,100)
pen.end_fill()
def txt():
    pen.up()
    pen.setpos(-30,100)
    pen.end_fill()
    pen.color('red')
    pen.write("I love chithruban",font=("bold",16))
    txt()
    pen.end_fill()
    t.exitonclick()